#pragma once

#include "mtrk.h"

#include "ChannelAnalyzer.hpp"
#include "Utils.hpp"

#include "boost/log/trivial.hpp"

#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>

class MikrotikConfig
{
public:
    bool comments = false;
    uint16_t ppqn;
    int32_t bpm;
    uint64_t track_index = 0;
    PitchShift pitchShift;
    std::string inFileName = "";
    std::string outFileName = "";
};

class MikrotikTrack
{
public:
    MikrotikTrack(MikrotikConfig &config, ChannelAnalyzer &analyzer) : m_config(config), m_analyzer(analyzer)
    {
    }
    void getScriptHeader(std::ofstream &out)
    {
        out << "#----------------File Description-----------------#\n";
        out << "# This file generated by Midi To Mikrotik Converter\n";
        out << "# Visit app repo: https://github.com/altucor/midi_to_mikrotik_converter\n";
        out << "# Original midi file name/path: " << m_config.inFileName << "\n";
        out << "# Track BPM: " << std::to_string(m_config.bpm) << "\n";
        out << "# MIDI Channel: " << std::to_string(m_analyzer.channel()) << "\n";
        out << "# Number of notes: " << m_analyzer.notesCount() << "\n";
        out << "# Track length: " << m_analyzer.duration() << "\n";
        // out << "# Track name: " << m_track.getName() << "\n";
        // out << "# Instrument name: " << m_track.getInstrumentName() << "\n";
        // out << "# Track text: " << chunk.mtrkChunkHandler.getTrackText() << "\n";
        // out << "# Track copyright: " << chunk.mtrkChunkHandler.getCopyright() << "\n";
        // out << "# Vocals: " << chunk.mtrkChunkHandler.getInstrumentName() << "\n";
        // out << "# Text marker: " << chunk.mtrkChunkHandler.getTextMarker() << "\n";
        // out << "# Cue Point: " << chunk.mtrkChunkHandler.getCuePoint() << "\n";
        out << "#-------------------------------------------------#\n\n";
    }

    int exportScript()
    {
        /*
         * later_bitches.mid
         * later_bitches-3xOsc-1-0.txt
         */

        if (m_analyzer.notesCount() == 0)
        {
            return 0;
        }

        std::string outFileName(m_config.outFileName);
        outFileName += "-";
        // outFileName += m_track.getName();
        outFileName += "-";
        // outFileName += std::to_string(track_index);
        outFileName += "-";
        outFileName += std::to_string(m_analyzer.channel());
        outFileName += ".txt";

        std::ofstream outputFile;
        outputFile.open(outFileName);
        if (!outputFile.is_open())
        {
            BOOST_LOG_TRIVIAL(info) << "[MikrotikTrack] export failed cannot create output file: " << outFileName;
            return -1;
        }

        // BOOST_LOG_TRIVIAL(info) << "[MikrotikTrack] export started for track: " << m_index << " channel: " << (uint32_t)channel;
        getScriptHeader(outputFile);
        m_analyzer.toScript(outputFile);

        BOOST_LOG_TRIVIAL(info) << "[MikrotikTrack] export finished";
        return 0;
    }

private:
    MikrotikConfig m_config = {0};
    ChannelAnalyzer m_analyzer;
};
